### ISSUE TITLE
Umm, no picture is posted

### ISSUE THREAD

**Issue by qomiter** [DoubleHub/whos-that-pokemon#1]
when I play the game no picture is posted? 

[!wtp] Picking a random Pokemon!
{ form:
   { name: 'magneton',
     url: 'https://pokeapi.co/api/v2/pokemon-form/82/' },
  sprite:
   'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png' }
(node:240945) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (/home/qomiter/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:240945) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:240945) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by giovanni-orciuolo** [comment]
The error is likely located at this line of code: https://github.com/giovanni-orciuolo/whos-that-pokemon/blob/master/src/app.js#L57

This bot is 3 years old so it's very likely that Discord changed their API and now they don't accept empty messages with files anymore, there must be another way to send files. Sadly I don't have the time to properly research it (maybe it's easy though idk).
